# Generated by Django 3.2 on 2021-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
