# Generated by Django 3.2 on 2021-04-29 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210429_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100)),
                ('company_url', models.CharField(default='', max_length=100)),
                ('employment_type', models.CharField(choices=[('fulltime', 'Full Time'), ('freelance', 'Free Lance'), ('contrac', 'Contract')], default='fulltime', max_length=100)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(default='New York, NY', max_length=100)),
                ('job_title', models.CharField(default='Front End Engineer', max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(default=['react']),
        ),
    ]
