# Generated by Django 3.2 on 2021-04-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210429_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accomplishments',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('freelance', 'Free Lance'), ('contract', 'Contract')], default='fulltime', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
